development:
  adapter: postgresql
  database: aria_development
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: aria_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: aria_production
  pool: 5
  timeout: 5000
